### ISSUE TITLE
How to display the max value over time?

### ISSUE THREAD

**Issue by jaimeiniesta** [mirego/telemetry_ui#15]
Hi there!

I'm using `value_over_time` to display my duration measures, but I'd like to detect peaks.

How can I display the `max_value` instead of the average `value`?

**Comment by simonprev** [comment]
I just pushed an option to do just that, configure the "aggregate" used in the timeseries chart:

```elixir
value_over_time("phoenix.router_dispatch.stop.duration",
  description: "Requests duration over time",
  unit: {:native, :millisecond},
  options: %{aggregate: "max", aggregate_label: "Max"},
  ui_options: [unit: "ms"]
),
```

the aggregate is an operation mapped directly in Vega-lite: https://vega.github.io/vega-lite/docs/aggregate.html#ops
