### ISSUE TITLE
No stlying + javascript errors

### ISSUE THREAD

**Issue by Hermanverschooten** [mirego/telemetry_ui#16]
Hi,

I just added this to my Phoenix 1.0.0-rc.6 application and I am getting no styling, the `<style>` is empty.

And I get a number javascript errors 
```javascript
Uncaught TypeError: window.drawChart is not a function
    <anonymous> http://localhost:4000/metrics?filter[page]=:223
    EventListener.handleEvent* http://localhost:4000/metrics?filter[page]=:222
```

**Comment by simonprev** [comment]
Oh that was a refactor in the asset handling and not pushing the `priv/static/assets` on hex.pm! It’s now fixed in 4.4.2 😄
