### ISSUE TITLE
Crash with Ecto telemetry for repo.query.queue_time

### ISSUE THREAD

**Issue by jaimeiniesta** [mirego/telemetry_ui#8]
Hi!

In the Live Dashboard I have these metrics and they work fine:

```
      # Database Time Metrics
      summary("myapp.repo.query.total_time", unit: {:native, :millisecond}),
      summary("myapp.repo.query.decode_time", unit: {:native, :millisecond}),
      summary("myapp.repo.query.query_time", unit: {:native, :millisecond}),
      summary("myapp.repo.query.queue_time", unit: {:native, :millisecond}),
      summary("myapp.repo.query.idle_time", unit: {:native, :millisecond}),
```

However, if I try to add them to Telemetry UI like this:

```
value_over_time(
          "myapp.repo.query.total_time",
          description: "Repo Query Queue Time",
          unit: {:native, :millisecond},
          ui_options: [unit: " ms"]
        )
```

It crashes with:

```
** (ArithmeticError) bad argument in arithmetic expression
    :erlang.+(nil, 0.716)
    (telemetry_ui 0.0.18) lib/telemetry_ui/write_buffer.ex:85: anonymous fn/2 in TelemetryUI.WriteBuffer.group_events/2
    (elixir 1.13.4) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (telemetry_ui 0.0.18) lib/telemetry_ui/write_buffer.ex:85: anonymous fn/2 in TelemetryUI.WriteBuffer.group_events/2
    (stdlib 3.14.2.2) maps.erl:233: :maps.fold_1/3
    (telemetry_ui 0.0.18) lib/telemetry_ui/write_buffer.ex:72: TelemetryUI.WriteBuffer.do_flush/2
    (stdlib 3.14.2.2) gen_server.erl:727: :gen_server.try_terminate/3
    (stdlib 3.14.2.2) gen_server.erl:912: :gen_server.terminate/10
    (stdlib 3.14.2.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

This is failing both with `queue_time` and `decode_time`, but works fine with `total_time` and `query_time`.

Any idea why this may be failing and how to fix that?

Thanks!

**Comment by simonprev** [comment]
Hello! The issue is that Ecto emit a telemetry event with a "duration" as `nil` instead of `0` when the queue does not wait.

So instead of assuming that `nil` is `0` everywhere in TelemetryUI, we added a reporter option in https://github.com/mirego/telemetry_ui/commit/c01f1217e77da2d92d263da50f6a6d8896c43504

So your example should be:

```elixir
cast_value = fn
  nil -> 0
  value -> value
end

value_over_time(
  "myapp.repo.query.queue_time",
  description: "Repo Query Total Time",
  unit: {:native, :millisecond},
  reporter_options: [cast_value: cast_value],
  ui_options: [unit: " ms"]
)
```

This is in the 1.1.3 release 😃

**Comment by jaimeiniesta** [comment]
Thank you!

This seems to fix the issue, makes sense to cast this value.

**Comment by jaimeiniesta** [comment]
Hi again, sorry but it's not really fixed with this, now it doesn't crash and there are no error logs, but it doesn't track that event (although it appears on the live dashboard). Here's my config, I've added that `IO.inspect` to check that it does cast the values but I don't see anything for that. If I cast the values on the other metrics that work like `myapp.repo.query.total_time` I do see the debug output.

```
defp telemetry_config do
  import TelemetryUI.Metrics

  cast_value = fn
    nil -> 0 |> IO.inspect(label: "cast")
    value -> value |> IO.inspect(label: "cast")
  end

  [
    metrics: [
      value_over_time("vm.memory.total", unit: {:byte, :megabyte}),
      value_over_time(
        "myapp.repo.query.total_time",
        description: "Repo Query Total Time",
        unit: {:native, :millisecond},
        ui_options: [unit: " ms"]
      ),
      value_over_time(
        "myapp.repo.query.queue_time",
        description: "Repo Queue Time",
        unit: {:native, :millisecond},
        reporter_options: [cast_value: cast_value],
        ui_options: [unit: " ms"]
      )
  ]
end
```

**Comment by jaimeiniesta** [comment]
Here are some screenshots in case it helps :)

<img width="564" alt="Captura de pantalla 2022-12-02 a las 20 07 50" src="https://user-images.githubusercontent.com/2629/205367566-3fe13045-8060-45f0-8ab5-b5b6800d8061.png">

<img width="1174" alt="Captura de pantalla 2022-12-02 a las 20 08 06" src="https://user-images.githubusercontent.com/2629/205367581-2ba53001-0b5d-4370-b813-ec604cafca2a.png">
